/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filechooser;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.FILES_AND_DIRECTORIES;

/**
 *
 * @author mac
 */
public class Filechooser extends javax.swing.JFrame  {
 
    public Filechooser() {
        super("choose file");
        initComponents();
        getinfo.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        getinfo = new javax.swing.JTextArea();
        clearButton = new javax.swing.JButton();
        chooseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getinfo.setBackground(new java.awt.Color(204, 204, 204));
        getinfo.setColumns(20);
        getinfo.setRows(5);
        getinfo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jScrollPane1.setViewportView(getinfo);

        clearButton.setBackground(new java.awt.Color(128, 166, 205));
        clearButton.setFont(new java.awt.Font("PingFang HK", 0, 14)); // NOI18N
        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        chooseButton.setBackground(new java.awt.Color(128, 166, 205));
        chooseButton.setFont(new java.awt.Font("PingFang HK", 0, 14)); // NOI18N
        chooseButton.setText("choose a file or directory");
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(chooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
      
        getinfo.setText(" ");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
  JFileChooser x;
           x=new JFileChooser();
           x.setFileSelectionMode(FILES_AND_DIRECTORIES);
        int f= x.showOpenDialog(this);
         if(f==JFileChooser.APPROVE_OPTION){
 File t = x.getSelectedFile();
 if(t.isFile()){
    
     try {
           getinfo.append("Kind : File . "+ "\n");
         fileInfo(t);
     } catch (IOException ex) {
         Logger.getLogger(Filechooser.class.getName()).log(Level.SEVERE, null, ex);
     }
 
 }
 else if(t.isDirectory()){
     try {
         directoryInfo(t);
     } catch (IOException ex) {
         Logger.getLogger(Filechooser.class.getName()).log(Level.SEVERE, null, ex);
     }
 }
         }      // TODO add your handling code here:
    }//GEN-LAST:event_chooseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filechooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filechooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filechooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filechooser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filechooser().setVisible(true);
            }
        });
    }
    public void fileInfo(File f) throws IOException{
        getinfo.append(" Canonical Path : "+f.getCanonicalPath());
 getinfo.append("\n");
    getinfo.append("Readable :"+f.canRead());
 getinfo.append("\n");
 getinfo.append("Writable:"+ f.canWrite()+"\n");
 getinfo.append(" Name :"+f.getName());
 getinfo.append("\n");
 
  getinfo.append("Size: "+ f.length()+"bytes"+"\n");
  
  getinfo.append("-----------------------------------------------------------------\n");
    }
public void directoryInfo(File f) throws IOException{
  getinfo.append("Kind: Directory "+ "\n");
  getinfo.append("Absolute Path: "+ f.getAbsolutePath()+"\n");
        fileInfo(f);
        File[] files = f.listFiles();
        if (files != null) {
            for (File file : files) {
                if (file.isDirectory()) {
                    directoryInfo(file);
                } 
                else {
                    getinfo.append("Kind : File ."+ "\n");
                    fileInfo(file);
                }
            }
        }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextArea getinfo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
